---
- name: sudoers | Create sudoers directory
  file:
    path: /etc/sudoers.d
    state: directory
    mode: '0750'

- name: sudoers | Configure sudoers entries
  lineinfile:
    path: /etc/sudoers
    line: "{{ item.1 }}"
    state: "{{ sudoers[item.0.key].state }}"
    validate: "visudo -cf %s"
  loop: "{{ sudoers | dict2items | subelements('value.lines') }}"
  loop_control:
    label: "{{ item.1 }}"
